---
controller_manager:
  ros__parameters:
    update_rate: 60
    use_sim_time: true
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
    omni_wheel_drive_controller:
      type: omni_wheel_drive_controller/OmniWheelDriveController
omni_wheel_drive_controller:
  ros__parameters:
    wheel_offset: 3.92698163
    wheel_names:
      - omni_wheel_joint_1
      - omni_wheel_joint_3
      - omni_wheel_joint_4
      - omni_wheel_joint_2


      #  wheel_names:
      # [
      #   "front_wheel_joint",
      #   "left_wheel_joint",
      #   "back_wheel_joint",
      #   "right_wheel_joint",
      # ]

    robot_radius: 0.252
    wheel_radius: 0.076
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal:
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
    twist_covariance_diagonal:
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
      - 0.01
    open_loop: true
    position_feedback: false
    enable_odom_tf: true
    cmd_vel_timeout: 0.5
    publish_limited_velocity: true